Repository JuliaDataScience/JuliaDataScience, pull requests merged in 2021-08, with the labels that each got.

#58 added draft for color and colormaps in Makie
  Project.toml
  config.toml
  contents/data_vis.md
  contents/plots.md
  src/JDS.jl
  src/makie.jl
Labels: writing

#64 Added splatting operator to Julia 101
  contents/julia_101.md
Labels: writing

#71 fixed spelling for use case and mix and match
  contents/julia_101.md
  contents/why_julia.md
Labels: spelling

#92 added funding button
  .github/FUNDING.yml
Labels: enhancement
